# Generated by Django 4.1.3 on 2023-01-04 09:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='media',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
