# Generated by Django 4.1.3 on 2023-01-04 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0002_blogs_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='media',
            field=models.FileField(upload_to=''),
        ),
    ]
