# Generated by Django 4.1.3 on 2023-01-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0003_alter_blogs_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expertsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('contact', models.TextField()),
                ('avtar', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Fertilizermodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('media', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Newsmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('media', models.FileField(upload_to='')),
            ],
        ),
    ]
