# Generated by Django 4.1.3 on 2023-01-08 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginregister', '0006_remove_company_user_company_email_company_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fertilizermodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
