# Generated by Django 4.1.3 on 2023-02-01 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loginregister', '0007_fertilizermodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='expertsmodel',
            name='email',
            field=models.EmailField(default=django.utils.timezone.now, max_length=254),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AppointmentScheduleModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titile', models.TextField()),
                ('appointmentDate', models.TextField()),
                ('description', models.TextField()),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='loginregister.expertsmodel')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
