# Generated by Django 4.1.3 on 2023-02-01 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginregister', '0008_expertsmodel_email_appointmentschedulemodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointmentschedulemodel',
            old_name='titile',
            new_name='title',
        ),
    ]
